# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# https://docs.github.com/cn/actions/learn-github-actions/contexts#github-context
name: test-nginx

on:
  push:
    branches:
      - main
    tags:
      - v*


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: BuildDockerImage
        run: docker build . --file Dockerfile --tag kevin0217/testgit:${{ github.ref_name	 }}
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kevin0217/testgit:${{ github.ref_name	 }}
          repository: kevin0217/testgit
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true